server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: b722NJQVDCQFYYb7HY5PoYkKDxYWY71Z #check before server start
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/keycloak #/login/oauth/code -> fixed path, also set to keycloak
#            scope: openid,email,profile #client scopes에 openid를 추가하고 나서 oauth2-client-app에서 client scope에 openid를 추가해도 됨
#            client-name: oauth2-client-app
#            client-authentication-method: client_secret_basic #client_secret_post, none

        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/oauth2
#            authorization-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/auth
#            token-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/token

#            user-info-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/userinfo
#            jwk-set-uri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs #for public key
#            user-name-attribute: preferred_username #it depends on provider
